version: "3"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    command: npm run start-nodemon
    stdin_open: true # хз зачем нужны, как-то дев фронта с ними робит
    tty: true
    volumes:
      - ./api/src:/usr/src/app/src
